### ISSUE TITLE
Datenerfassung für BalkonPV

### ISSUE THREAD

**Issue by ehorvat1** [hegessne/pv-balkonkraftwerk#8]
Servus Hendrik, ich habe mich auch mit Balkon PVs beschäftigt und eine Möglichkeit der Datenerfassung gebastelt. Siehe: https://github.com/ehorvat1/Balkon-PV . 
Motivation war dass die kleinen Wechselrichter einer BalkonPV oft keine Anzeige haben, und die übliche Lösung über eine "Shelly" Steckdose war mir zu einfach :) . 
Als ich den Topic "Balkonpv" in mein Repository eingegeben habe bin ich auf dieses hier gestossen....
LG, Engelbert

**Comment by hegessne** [comment]
Hallo Engelbert, danke für Deine Nachricht und den Hinweis zur Datenerfassung.
Ich schaue mir das mal an - bin schon gespannt.
Danke und viele Grüße
Hendrik

**Comment by ehorvat1** [comment]
no coment
